# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net..
#

name: Check main branch
env:
  ACTIONS_RUNNER_DEBUG: true

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true
    
jobs:
  check_change:
    name: Check Change
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: 7.0.x
    - name: "Checkout GitHub Action"
      uses: actions/checkout@v3       
      
    - name: Restore dependencies
      run: dotnet restore ./WebApplication2/WebApplication3.csproj

    - name: Build
      run: dotnet build ./WebApplication2/WebApplication3.csproj --no-restore --configuration Release
 
  

    
    
