# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net..
#

name: Check main branch
env:
  ACTIONS_RUNNER_DEBUG: true

on:

  push:
    branches: ["master"]
    
jobs:
  build-and-deploy_1:
    uses: ./.github/workflows/build1.yml@main
  build-and-deploy_2:
    uses: ./.github/workflows/build2.yml@main
      
 
  

    
    
