# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net..
#

name: Check main branch


on:

  push:
    branches: ["master"]
    
env:
  PROJECT_PATH: "./WebApplication2/WebApplication2.csproj"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Dotnet Build
      run: dotnet build $PROJECT_PATH --configuration Release 
   
    - name: Dotnet Publish
      run: dotnet publish ./WebApplication2/WebApplication2.csproj -c Release  -o ./Release     
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-app-$(date +'%Y-%m-%d')-${{ github.run_attempt }}
        path: ./Release
    
    
