# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net..
#

name: Check main branch
env:
  ACTIONS_RUNNER_DEBUG: true

on:

  push:
    branches: ["master"]
    
jobs:
  build-and-deploy_1:
    uses: kenpi04/WebApplication2/.github/workflows/build-1.yml
  build-and-deploy_2:
    uses: kenpi04/WebApplication2/.github/workflows/build-2.yml
      
 
  

    
    
