# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net..
#

name: Check main branch
env:
  ACTIONS_RUNNER_DEBUG: true

on:

  push:
    branches: ["master"]
    
jobs:
  
  build-and-deploy_1:
    uses: ./.github/workflows/build-1.yml
  
  deploy_1:
    runs-on: windows-latest
    needs: build-and-deploy_1
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: web1-${{ github.run_number }}
          path: ./artifact

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./artifact
  
  build-and-deploy_2:  
    uses: ./.github/workflows/build-2.yml
  
  deploy_2:
      runs-on: windows-latest
      needs: build-and-deploy_2
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: web2-${{ github.run_number }}
            path: ./artifact
  
        - name: Display structure of downloaded files
          run: ls -R
          working-directory: ./artifact
      
 
  

    
    
